apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: starter-kit.online
  # Cert-Manager will put the resulting Secret in the same Kubernetes namespace as the Certificate.
  namespace: backend
spec:
  # Secret name to create, where the private key and certificate should be stored.
  secretName: starter-kit.online
  # What Issuer to use for getting the certificate.
  issuerRef:
    name: letsencrypt-nginx-wcard
    kind: Issuer
    group: cert-manager.io
  # Common name to be used on the Certificate.
  commonName: "*.starter-kit.online"
  # List of DNS subjectAltNames to be set on the Certificate.
  dnsNames:
    - "starter-kit.online"
    - "*.starter-kit.online"
