---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: http-listener
spec:
  port: 8080
  protocol: HTTPS
  # protocolStack:
  # - PROXY
  # - HTTP
  # - TCP
  securityModel: XFP
  statsPrefix: http-listener
  hostBinding:
    namespace:
      from: ALL
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: https-listener
spec:
  port: 8443
  protocol: HTTPS
  # protocolStack:
  # - PROXY
  # - TLS
  # - HTTP
  # - TCP
  securityModel: XFP
  statsPrefix: https-listener
  hostBinding:
    namespace:
      from: ALL
